### ISSUE TITLE
Enhance worldgen

### ISSUE THREAD

**Issue by benjamin-allen** [Nullsrc/GridRL#5]
- [x] Generate rooms in a more logical way
- [x] Fill the rest of the area with maze
- [x] Connect rooms and maze/rooms (separate floor/maze tiles might help here)
- [x] Selectively remove some dead-ends

**Comment by Nullsrc** [comment]
- [ ] Generate rooms in a more logical way
- [ ] Fill the rest of the area with maze
- [ ] Connect rooms and maze/rooms (separate floor/maze tiles might help here)
- [ ] Selectively remove some dead-ends

**Comment by benjamin-allen** [comment]
@sherryn18  check this out: d32c7f554d444a9f2345b9762c8c9515335b0fea

![capture](https://cloud.githubusercontent.com/assets/6005492/25905362/79af441c-3567-11e7-979c-d81a4c9f7f80.PNG)
