### ISSUE TITLE
Hover Descriptions

### ISSUE THREAD

**Issue by NoahSherry** [Nullsrc/GridRL#9]
Possibly implement and onMouseHover method for any given Actor like so:

```
protected override void onMouseHover {
    //Show text box above actor with this.Name + this.Description
}
```

Thoughts?

**Comment by benjamin-allen** [comment]
It might be worth consideration, but if onMouseHover proves to be too taxing we can probably get the same functionality with a onMouseClick

**Comment by benjamin-allen** [comment]
We're gonna do this with item descriptions and ability descriptions
